# Generated by Django 5.1 on 2024-08-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, default=None, null=True)),
                ('hour', models.TimeField(blank=True, default=None, null=True)),
                ('seats', models.IntegerField(default=80)),
                ('seats_platea', models.IntegerField(default=100)),
                ('seats_palco1', models.IntegerField(default=80)),
                ('seats_palco2', models.IntegerField(default=80)),
                ('seats_palco3', models.IntegerField(default=80)),
                ('seats_palco4', models.IntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Platea', 'platea'), ('Palco I', 'palco I'), ('Palco II', 'palco II'), ('Palco III', 'palco III'), ('Palco IV', 'palco IV')], max_length=10)),
                ('number', models.IntegerField(default=0)),
                ('occupied', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_booked', to='gestione.show')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('votes', models.IntegerField(default=0)),
                ('spectator', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL)),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gestione.show')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectator', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_made', to=settings.AUTH_USER_MODEL)),
                ('seats', models.ManyToManyField(related_name='booked', to='gestione.seat')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='gestione.show')),
            ],
        ),
    ]
