# Generated by Django 5.1 on 2024-08-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='data',
            new_name='date',
        ),
    ]
