# Generated by Django 5.1 on 2024-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_rename_data_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
