# Generated by Django 5.1 on 2024-09-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_alter_booking_show_alter_booking_spectator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
    ]
