# Generated by Django 5.1 on 2024-09-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_remove_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='booked', to='gestione.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='gestione.show'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seat_booked', to='gestione.show'),
        ),
    ]
