# Generated by Django 5.1 on 2024-09-03 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_booking_seats_alter_booking_show_alter_seat_show'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='spectator',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='free_seats_palco1',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='show',
            name='free_seats_palco2',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='show',
            name='free_seats_palco3',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='show',
            name='free_seats_palco4',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='show',
            name='free_seats_platea',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gestione.show'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=250)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gestione.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('show', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
