# Generated by Django 5.1 on 2024-09-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0008_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cover',
            field=models.ImageField(default='gestione/covers/default.webp', upload_to='gestione/covers'),
        ),
    ]
