# Generated by Django 5.1 on 2024-09-05 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_remove_booking_seats_count_remove_booking_seats_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_palco',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='seat_palco_cols',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='show',
            name='seat_palco_rows',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)]),
        ),
        migrations.AddField(
            model_name='show',
            name='seats_palco',
            field=models.JSONField(default=dict),
        ),
    ]
