# Generated by Django 5.1 on 2024-09-05 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0011_booking_seats_palco_booking_seats_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='seat_palco_rows',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)]),
        ),
    ]
