# Generated by Django 5.1 on 2024-09-05 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0012_alter_show_seat_palco_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats_palco',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seat_palco_cols',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seats_palco',
        ),
        migrations.AlterField(
            model_name='show',
            name='seat_rows',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)]),
        ),
    ]
