# Generated by Django 5.1 on 2024-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0014_alter_show_date_alter_show_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
