# Generated by Django 5.1 on 2024-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0015_alter_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
