# Generated by Django 5.1 on 2024-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0016_show_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats_type',
        ),
        migrations.AlterField(
            model_name='show',
            name='cover',
            field=models.ImageField(default='gestione/covers/default.png', upload_to='gestione/covers'),
        ),
    ]
